import { Project } from '@/lib/types';

export const projects: Project[] = [
  // ── COMMERCIAL ────────────────────────────────────────────────────────────
  {
    slug: 'ranch-hand',
    contentType: 'project',
    title: 'Built to Take a Hit',
    category: 'commercial',
    client: 'Ranch Hand',
    year: 2023,
    thumbnailGif: '/work/ranch-hand/preview.gif',
    thumbnailStill: '/work/ranch-hand/thumbnail.webp',
    featured: true,
    order: 1,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },
  {
    slug: 'downtown-dining-alliance',
    contentType: 'project',
    title: 'Taste The Difference',
    category: 'commercial',
    client: 'Downtown Dining Alliance',
    year: 2023,
    thumbnailGif: '/work/downtown-dining-alliance/preview.gif',
    thumbnailStill: '/work/downtown-dining-alliance/thumbnail.webp',
    featured: true,
    order: 2,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },
  {
    slug: 'viewrail',
    contentType: 'project',
    title: 'The Difference',
    category: 'commercial',
    client: 'Viewrail',
    year: 2023,
    thumbnailGif: '/work/viewrail/preview.gif',
    thumbnailStill: '/work/viewrail/thumbnail.webp',
    featured: false,
    order: 3,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },
  {
    slug: 'janus-motorcycles',
    contentType: 'project',
    title: 'Do Not Go Gentle',
    category: 'commercial',
    client: 'Janus Motorcycles',
    year: 2023,
    thumbnailGif: '/work/janus-motorcycles/preview.gif',
    thumbnailStill: '/work/janus-motorcycles/thumbnail.webp',
    featured: false,
    order: 4,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },
  {
    slug: 'we-you',
    contentType: 'project',
    title: 'Clay Bottom Farm',
    category: 'commercial',
    client: 'WE+YOU',
    year: 2023,
    thumbnailGif: '/work/we-you/preview.gif',
    thumbnailStill: '/work/we-you/thumbnail.webp',
    featured: true,
    order: 5,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },

  // ── DOCUMENTARY ───────────────────────────────────────────────────────────
  {
    slug: 'juneteenth-tv-special',
    contentType: 'project',
    title: 'A Juneteenth Celebration',
    category: 'documentary',
    client: 'South Bend Symphony Orchestra',
    year: 2021,
    thumbnailGif: '',
    thumbnailStill: '/work/juneteenth-tv-special/thumbnail.webp',
    featured: true,
    order: 6,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Chuck Fry' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Creative Director', name: 'Jacob Titus' },
    ],
  },
  {
    slug: 'ejm-stories',
    contentType: 'project',
    title: 'EJM Stories',
    category: 'documentary',
    client: 'EJM',
    year: 2023,
    thumbnailGif: '',
    thumbnailStill: '/work/ejm-stories/thumbnail.webp',
    featured: false,
    order: 7,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },
  {
    slug: 'south-bend',
    contentType: 'project',
    title: 'South Bend',
    category: 'documentary',
    client: 'City of South Bend',
    year: 2020,
    thumbnailGif: '',
    thumbnailStill: '/work/south-bend/thumbnail.webp',
    featured: false,
    order: 8,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },

  // ── MUSIC VIDEO ───────────────────────────────────────────────────────────
  {
    slug: 'pray',
    contentType: 'project',
    title: 'Pray',
    category: 'music-video',
    client: 'Independent',
    year: 2017,
    thumbnailGif: '/work/pray/preview.gif',
    thumbnailStill: '/work/pray/thumbnail.webp',
    featured: false,
    order: 9,
    video: { type: 'vimeo', id: 'PLACEHOLDER' },
    contributors: [
      { role: 'Director', name: 'Ryan Blaske' },
      { role: 'Cinematographer', name: 'Ryan Blaske' },
      { role: 'Editor', name: 'Ryan Blaske' },
    ],
  },
];
